document.getElementById('year').textContent = new Date().getFullYear();

const DATA_URL = '/latest_news.json';

async function fetchAndRenderNews() {
    const statusEl = document.getElementById('status-message');
    const contentEl = document.getElementById('news-content');

    try {
        // Fetch data from the local JSON file generated by backend
        const response = await fetch(DATA_URL);

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();

        // Hide status, show content
        statusEl.style.display = 'none';
        contentEl.style.display = 'block';

        // Update header
        const updatedDate = new Date(data.generatedAt);
        document.getElementById('last-updated').textContent = `Last Updated: ${updatedDate.toLocaleString('ja-JP')} (Local Time)`;

        renderHeadlines(data.headlines);
        renderSubNews(data.subNews);
        renderOtherNews(data.otherNews);

    } catch (error) {
        console.error("Error fetching news:", error);
        statusEl.textContent = "Failed to load news. Please make sure the backend script has been run to generate data.";
        statusEl.style.color = "#ff7b72"; // Error color (reddish)
    }
}

function formatDate(dateString) {
    if (!dateString) return 'Unknown Date';
    const d = new Date(dateString);
    return `${d.getMonth() + 1}/${d.getDate()} ${d.getHours()}:${String(d.getMinutes()).padStart(2, '0')}`;
}

function renderHeadlines(headlines) {
    const container = document.getElementById('headlines-grid');
    if (!headlines || headlines.length === 0) {
        container.innerHTML = '<p>No headlines available today.</p>';
        return;
    }

    container.innerHTML = headlines.map((news, index) => `
        <article class="glass-panel headline-card">
            <div class="card-source">${news.source}</div>
            <h3 class="card-title">
                <a href="${news.link}" target="_blank" rel="noopener noreferrer">${news.title}</a>
            </h3>
            <p class="card-summary">${news.summary}</p>
            <div class="card-meta">
                <span class="card-date">${formatDate(news.pubDate)}</span>
                <a href="${news.link}" target="_blank" rel="noopener noreferrer" class="read-more">Read Source <span>→</span></a>
            </div>
        </article>
    `).join('');
}

function renderSubNews(subNews) {
    const container = document.getElementById('subnews-list');
    if (!subNews || subNews.length === 0) {
        container.innerHTML = '<p>No sub news available.</p>';
        return;
    }

    container.innerHTML = subNews.map(news => `
        <a href="${news.link}" target="_blank" rel="noopener noreferrer" class="list-item">
            <div class="list-item-title">${news.title}</div>
            ${news.summary ? `<div class="list-item-summary">${news.summary}</div>` : ''}
            <div class="list-item-meta">
                <span class="source-badge">${news.source}</span>
                <span>${formatDate(news.pubDate)}</span>
            </div>
        </a>
    `).join('');
}

function renderOtherNews(otherNews) {
    const container = document.getElementById('othernews-list');
    if (!otherNews || otherNews.length === 0) {
        container.innerHTML = '<p>No other news available.</p>';
        return;
    }

    container.innerHTML = otherNews.map(news => `
        <a href="${news.link}" target="_blank" rel="noopener noreferrer" class="list-item">
            <div class="list-item-title" title="${news.title}">${news.title}</div>
            <div class="source-badge">${news.source}</div>
        </a>
    `).join('');
}

// Initialize
document.addEventListener('DOMContentLoaded', fetchAndRenderNews);
